### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by o-moridon** [o-moridon/furima-39741#21]
# URL
https://furima-39741.onrender.com/
# Basic認証のIDとパスワード
ID : admin , pass : 2222
# 出品者用のメールアドレスとパスワード
email : furima123@taro.org , pass : 123qwe
# 購入者用のメールアドレスとパスワード
email : test1991@gmail.com , pass : 123qwe

**Comment by shodai-ito** [comment]
@o-moridon さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されること（--- は初期値として設定すること）**
不要な「・」があるため削除をお願いします。
<img width="581" alt="スクリーンショット 2023-09-04 9 37 35" src="https://github.com/o-moridon/furima-39741/assets/62537107/8fb1e31c-287a-40ea-9934-5e8a3898c2fa">

- [x] **商品出品時とほぼ同じ見た目の商品情報編集ページが表示されること**
出品ページと比較して、レイアウトが崩れているプルダウンが存在します。
<img width="573" alt="スクリーンショット 2023-09-04 9 37 56" src="https://github.com/o-moridon/furima-39741/assets/62537107/8de4243b-c7c1-4be9-a94c-3195ebd8c540">

- [x] **クレジットカードの情報は購入の都度入力させること**
一度購入に失敗すると、それ以降クレジットカード情報が入力できなくなってしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by o-moridon** [comment]
ありがとうございます。

修正完了いたしました。
本番環境でも３点確認済みです。
挙動確認依頼フォームも提出しました。

ご確認よろしくお願いします。

**Comment by moom1122** [comment]
@o-moridon さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
